CREATE TABLE accounts (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, username VARCHAR(80) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL, role VARCHAR(16) NOT NULL, owner_id INT UNIQUE REFERENCES owners(id),
  must_change_password BOOLEAN NOT NULL DEFAULT FALSE, temporary_password_expires_at TIMESTAMP WITH TIME ZONE,
  failed_sign_in_count INT NOT NULL DEFAULT 0, locked_until TIMESTAMP WITH TIME ZONE, version BIGINT NOT NULL DEFAULT 0
);
CREATE TABLE clinic_scheduling_settings (
  id INT PRIMARY KEY, clinic_zone VARCHAR(64) NOT NULL, booking_horizon_days INT NOT NULL,
  owner_minimum_notice_minutes INT NOT NULL, offer_hold_minutes INT NOT NULL,
  urgent_care_guidance VARCHAR(2000) NOT NULL, version BIGINT NOT NULL DEFAULT 0
);
INSERT INTO clinic_scheduling_settings VALUES (1, 'Europe/Amsterdam', 90, 120, 10, 'If your pet needs urgent care, contact the clinic or an emergency veterinarian immediately.', 0);
CREATE TABLE named_day_periods (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(80) NOT NULL UNIQUE, start_time TIME NOT NULL,
  end_time TIME NOT NULL, version BIGINT NOT NULL DEFAULT 0
);
CREATE TABLE recurring_vet_shifts (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, vet_id INT NOT NULL REFERENCES vets(id), day_of_week INT NOT NULL,
  start_time TIME NOT NULL, end_time TIME NOT NULL, version BIGINT NOT NULL DEFAULT 0
);
CREATE TABLE vet_availability_exceptions (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, vet_id INT NOT NULL REFERENCES vets(id), start_date DATE NOT NULL,
  end_date DATE NOT NULL, available BOOLEAN NOT NULL, start_time TIME, end_time TIME, reason VARCHAR(255), version BIGINT NOT NULL DEFAULT 0
);
CREATE TABLE vet_leaves (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, vet_id INT NOT NULL REFERENCES vets(id), start_date DATE NOT NULL,
  end_date DATE NOT NULL, reason VARCHAR(255), version BIGINT NOT NULL DEFAULT 0
);
CREATE TABLE clinic_closures (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, start_date DATE NOT NULL, end_date DATE NOT NULL,
  reason VARCHAR(255), version BIGINT NOT NULL DEFAULT 0
);
CREATE TABLE scheduling_requests (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, pet_id INT NOT NULL REFERENCES pets(id), state VARCHAR(32) NOT NULL,
  current_revision_id INT, emergency_priority BOOLEAN NOT NULL DEFAULT FALSE, version BIGINT NOT NULL DEFAULT 0
);
CREATE TABLE request_revisions (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, request_id INT NOT NULL REFERENCES scheduling_requests(id), revision_number INT NOT NULL,
  source_text VARCHAR(2000) NOT NULL, consent_given BOOLEAN NOT NULL, consent_at TIMESTAMP WITH TIME ZONE, raw_interpretation TEXT,
  model_identifier VARCHAR(255), correlation_id VARCHAR(80) NOT NULL, visit_reason VARCHAR(1000), duration_minutes INT, care_type VARCHAR(80),
  required_specialty VARCHAR(80), preferred_vet_id INT REFERENCES vets(id), urgency VARCHAR(32), confirmed_at TIMESTAMP WITH TIME ZONE,
  status VARCHAR(32) NOT NULL, version BIGINT NOT NULL DEFAULT 0, UNIQUE (request_id, revision_number)
);
ALTER TABLE scheduling_requests ADD FOREIGN KEY (current_revision_id) REFERENCES request_revisions(id);
CREATE TABLE request_availability_windows (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, revision_id INT NOT NULL REFERENCES request_revisions(id), kind VARCHAR(16) NOT NULL,
  applicable_date DATE, day_of_week INT, start_time TIME NOT NULL, end_time TIME NOT NULL, source VARCHAR(32) NOT NULL
);
CREATE TABLE appointment_offers (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, revision_id INT NOT NULL REFERENCES request_revisions(id), vet_id INT NOT NULL REFERENCES vets(id),
  start_at TIMESTAMP WITH TIME ZONE NOT NULL, duration_minutes INT NOT NULL, offered_at TIMESTAMP WITH TIME ZONE NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL, state VARCHAR(16) NOT NULL, rationale VARCHAR(1000) NOT NULL,
  rejection_reason VARCHAR(255), version BIGINT NOT NULL DEFAULT 0, UNIQUE (revision_id, vet_id, start_at)
);
CREATE TABLE appointments (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, pet_id INT NOT NULL REFERENCES pets(id), vet_id INT NOT NULL REFERENCES vets(id),
  start_at TIMESTAMP WITH TIME ZONE NOT NULL, duration_minutes INT NOT NULL, source VARCHAR(32) NOT NULL,
  request_id INT REFERENCES scheduling_requests(id), revision_id INT REFERENCES request_revisions(id), offer_id INT UNIQUE REFERENCES appointment_offers(id),
  owner_agreement VARCHAR(1000), status VARCHAR(16) NOT NULL, change_reason VARCHAR(64), change_note VARCHAR(1000), version BIGINT NOT NULL DEFAULT 0
);
CREATE TABLE reservation_blocks (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, resource_type VARCHAR(16) NOT NULL, resource_id INT NOT NULL,
  slot_start TIMESTAMP WITH TIME ZONE NOT NULL, owner_type VARCHAR(16) NOT NULL, owner_id INT NOT NULL, state VARCHAR(16) NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE, UNIQUE (resource_type, resource_id, slot_start)
);
CREATE TABLE staff_queue_items (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, request_id INT NOT NULL UNIQUE REFERENCES scheduling_requests(id), state VARCHAR(32) NOT NULL,
  priority VARCHAR(16) NOT NULL, claimed_by_account_id INT REFERENCES accounts(id), resolution_details VARCHAR(1000), version BIGINT NOT NULL DEFAULT 0
);
CREATE TABLE scheduling_audit_records (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, occurred_at TIMESTAMP WITH TIME ZONE NOT NULL, correlation_id VARCHAR(80),
  actor_account_id INT REFERENCES accounts(id), actor VARCHAR(80) NOT NULL, action VARCHAR(64) NOT NULL, target_type VARCHAR(64) NOT NULL,
  target_id VARCHAR(80) NOT NULL, prior_value TEXT, resulting_value TEXT, reason VARCHAR(1000)
);
ALTER TABLE visits ADD appointment_id INT UNIQUE, ADD vet_id INT, ADD completed_at TIMESTAMP WITH TIME ZONE, ADD clinical_notes VARCHAR(2000);
ALTER TABLE visits ADD FOREIGN KEY (appointment_id) REFERENCES appointments(id), ADD FOREIGN KEY (vet_id) REFERENCES vets(id);
