CREATE TABLE IF NOT EXISTS scheduling_requests (
  id                   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version              INT NOT NULL DEFAULT 0,
  owner_id             INT NOT NULL REFERENCES owners (id),
  pet_id               INT NOT NULL REFERENCES pets (id),
  state                VARCHAR(30) NOT NULL,
  queue_reason         VARCHAR(50),
  raw_text             TEXT,
  interpretation_json  TEXT,
  ai_consent           BOOLEAN NOT NULL DEFAULT FALSE,
  preferred_date_start DATE,
  preferred_date_end   DATE,
  active_pet_key       INT,
  created_at           TIMESTAMP,
  updated_at           TIMESTAMP,
  queued_at            TIMESTAMP,
  CONSTRAINT uk_scheduling_requests_active_pet UNIQUE (active_pet_key)
);
CREATE INDEX IF NOT EXISTS idx_scheduling_requests_state ON scheduling_requests (state);
CREATE INDEX IF NOT EXISTS idx_scheduling_requests_owner ON scheduling_requests (owner_id);
CREATE INDEX IF NOT EXISTS idx_scheduling_requests_pet ON scheduling_requests (pet_id);
