CREATE TABLE IF NOT EXISTS slot_occupancy (
  id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vet_id         INT NOT NULL REFERENCES vets (id),
  start_time     TIMESTAMP NOT NULL,
  end_time       TIMESTAMP NOT NULL,
  occupancy_type VARCHAR(20) NOT NULL,
  reference_id   INT,
  created_at     TIMESTAMP,
  CONSTRAINT uk_slot_occupancy_vet_start UNIQUE (vet_id, start_time)
);
CREATE INDEX IF NOT EXISTS idx_slot_occupancy_vet_time ON slot_occupancy (vet_id, start_time);

CREATE TABLE IF NOT EXISTS holds (
  id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version      INT NOT NULL DEFAULT 0,
  request_id   INT NOT NULL REFERENCES scheduling_requests (id),
  vet_id       INT NOT NULL REFERENCES vets (id),
  start_time   TIMESTAMP NOT NULL,
  end_time     TIMESTAMP NOT NULL,
  expires_at   TIMESTAMP NOT NULL,
  status       VARCHAR(20) NOT NULL,
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_holds_request ON holds (request_id);
CREATE INDEX IF NOT EXISTS idx_holds_status_expires ON holds (status, expires_at);

CREATE TABLE IF NOT EXISTS appointments (
  id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version      INT NOT NULL DEFAULT 0,
  owner_id     INT NOT NULL REFERENCES owners (id),
  pet_id       INT NOT NULL REFERENCES pets (id),
  vet_id       INT NOT NULL REFERENCES vets (id),
  request_id   INT REFERENCES scheduling_requests (id),
  start_time   TIMESTAMP NOT NULL,
  end_time     TIMESTAMP NOT NULL,
  status       VARCHAR(30) NOT NULL,
  reason       VARCHAR(255),
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_appointments_owner ON appointments (owner_id);
CREATE INDEX IF NOT EXISTS idx_appointments_pet ON appointments (pet_id);
CREATE INDEX IF NOT EXISTS idx_appointments_vet_time ON appointments (vet_id, start_time);
