CREATE TABLE IF NOT EXISTS user_account (
  id                   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username             VARCHAR(100) NOT NULL,
  password             VARCHAR(255) NOT NULL,
  role                 VARCHAR(20) NOT NULL,
  must_change_password BOOLEAN NOT NULL DEFAULT FALSE,
  owner_id             INT REFERENCES owners (id),
  CONSTRAINT uk_user_account_username UNIQUE (username)
);
CREATE INDEX IF NOT EXISTS idx_user_account_username ON user_account (username);
CREATE INDEX IF NOT EXISTS idx_user_account_owner ON user_account (owner_id);
