CREATE TABLE IF NOT EXISTS vet_weekly_shift (
  id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vet_id      INT NOT NULL REFERENCES vets (id),
  day_of_week VARCHAR(20) NOT NULL,
  start_time  TIME NOT NULL,
  end_time    TIME NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_vet_weekly_shift_vet_day ON vet_weekly_shift (vet_id, day_of_week);

CREATE TABLE IF NOT EXISTS vet_date_exception (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vet_id     INT NOT NULL REFERENCES vets (id),
  start_date DATE NOT NULL,
  end_date   DATE NOT NULL,
  type       VARCHAR(30) NOT NULL,
  start_time TIME,
  end_time   TIME,
  reason     VARCHAR(255)
);
CREATE INDEX IF NOT EXISTS idx_vet_date_exception_vet_dates ON vet_date_exception (vet_id, start_date, end_date);

CREATE TABLE IF NOT EXISTS clinic_closure (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  start_date DATE NOT NULL,
  end_date   DATE NOT NULL,
  reason     VARCHAR(255),
  start_time TIME,
  end_time   TIME
);
CREATE INDEX IF NOT EXISTS idx_clinic_closure_dates ON clinic_closure (start_date, end_date);

-- Seed default shifts for vets 1 to 6 (Monday through Friday 08:00 - 17:00)
INSERT INTO vet_weekly_shift (vet_id, day_of_week, start_time, end_time) VALUES (1, 'MONDAY', '08:00:00', '17:00:00');
INSERT INTO vet_weekly_shift (vet_id, day_of_week, start_time, end_time) VALUES (1, 'TUESDAY', '08:00:00', '17:00:00');
INSERT INTO vet_weekly_shift (vet_id, day_of_week, start_time, end_time) VALUES (1, 'WEDNESDAY', '08:00:00', '17:00:00');
INSERT INTO vet_weekly_shift (vet_id, day_of_week, start_time, end_time) VALUES (1, 'THURSDAY', '08:00:00', '17:00:00');
INSERT INTO vet_weekly_shift (vet_id, day_of_week, start_time, end_time) VALUES (1, 'FRIDAY', '08:00:00', '17:00:00');

INSERT INTO vet_weekly_shift (vet_id, day_of_week, start_time, end_time) VALUES (2, 'MONDAY', '08:00:00', '17:00:00');
INSERT INTO vet_weekly_shift (vet_id, day_of_week, start_time, end_time) VALUES (2, 'TUESDAY', '08:00:00', '17:00:00');
INSERT INTO vet_weekly_shift (vet_id, day_of_week, start_time, end_time) VALUES (2, 'WEDNESDAY', '08:00:00', '17:00:00');
INSERT INTO vet_weekly_shift (vet_id, day_of_week, start_time, end_time) VALUES (2, 'THURSDAY', '08:00:00', '17:00:00');
INSERT INTO vet_weekly_shift (vet_id, day_of_week, start_time, end_time) VALUES (2, 'FRIDAY', '08:00:00', '17:00:00');

INSERT INTO vet_weekly_shift (vet_id, day_of_week, start_time, end_time) VALUES (3, 'MONDAY', '08:00:00', '17:00:00');
INSERT INTO vet_weekly_shift (vet_id, day_of_week, start_time, end_time) VALUES (3, 'TUESDAY', '08:00:00', '17:00:00');
INSERT INTO vet_weekly_shift (vet_id, day_of_week, start_time, end_time) VALUES (3, 'WEDNESDAY', '08:00:00', '17:00:00');
INSERT INTO vet_weekly_shift (vet_id, day_of_week, start_time, end_time) VALUES (3, 'THURSDAY', '08:00:00', '17:00:00');
INSERT INTO vet_weekly_shift (vet_id, day_of_week, start_time, end_time) VALUES (3, 'FRIDAY', '08:00:00', '17:00:00');

INSERT INTO vet_weekly_shift (vet_id, day_of_week, start_time, end_time) VALUES (4, 'MONDAY', '08:00:00', '17:00:00');
INSERT INTO vet_weekly_shift (vet_id, day_of_week, start_time, end_time) VALUES (4, 'TUESDAY', '08:00:00', '17:00:00');
INSERT INTO vet_weekly_shift (vet_id, day_of_week, start_time, end_time) VALUES (4, 'WEDNESDAY', '08:00:00', '17:00:00');
INSERT INTO vet_weekly_shift (vet_id, day_of_week, start_time, end_time) VALUES (4, 'THURSDAY', '08:00:00', '17:00:00');
INSERT INTO vet_weekly_shift (vet_id, day_of_week, start_time, end_time) VALUES (4, 'FRIDAY', '08:00:00', '17:00:00');

INSERT INTO vet_weekly_shift (vet_id, day_of_week, start_time, end_time) VALUES (5, 'MONDAY', '08:00:00', '17:00:00');
INSERT INTO vet_weekly_shift (vet_id, day_of_week, start_time, end_time) VALUES (5, 'TUESDAY', '08:00:00', '17:00:00');
INSERT INTO vet_weekly_shift (vet_id, day_of_week, start_time, end_time) VALUES (5, 'WEDNESDAY', '08:00:00', '17:00:00');
INSERT INTO vet_weekly_shift (vet_id, day_of_week, start_time, end_time) VALUES (5, 'THURSDAY', '08:00:00', '17:00:00');
INSERT INTO vet_weekly_shift (vet_id, day_of_week, start_time, end_time) VALUES (5, 'FRIDAY', '08:00:00', '17:00:00');

INSERT INTO vet_weekly_shift (vet_id, day_of_week, start_time, end_time) VALUES (6, 'MONDAY', '08:00:00', '17:00:00');
INSERT INTO vet_weekly_shift (vet_id, day_of_week, start_time, end_time) VALUES (6, 'TUESDAY', '08:00:00', '17:00:00');
INSERT INTO vet_weekly_shift (vet_id, day_of_week, start_time, end_time) VALUES (6, 'WEDNESDAY', '08:00:00', '17:00:00');
INSERT INTO vet_weekly_shift (vet_id, day_of_week, start_time, end_time) VALUES (6, 'THURSDAY', '08:00:00', '17:00:00');
INSERT INTO vet_weekly_shift (vet_id, day_of_week, start_time, end_time) VALUES (6, 'FRIDAY', '08:00:00', '17:00:00');
