spring.datasource.url=jdbc:h2:file:./data/petclinic-demo
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.sql.init.mode=never
spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate
