CREATE TABLE vets (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name VARCHAR(30),
  last_name  VARCHAR(30)
);
CREATE INDEX vets_last_name ON vets (last_name);

CREATE TABLE specialties (
  id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(80)
);
CREATE INDEX specialties_name ON specialties (name);

CREATE TABLE vet_specialties (
  vet_id       INTEGER NOT NULL,
  specialty_id INTEGER NOT NULL
);
ALTER TABLE vet_specialties ADD CONSTRAINT fk_vet_specialties_vets FOREIGN KEY (vet_id) REFERENCES vets (id);
ALTER TABLE vet_specialties ADD CONSTRAINT fk_vet_specialties_specialties FOREIGN KEY (specialty_id) REFERENCES specialties (id);

CREATE TABLE types (
  id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(80)
);
CREATE INDEX types_name ON types (name);

CREATE TABLE owners (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name VARCHAR(30),
  last_name  VARCHAR_IGNORECASE(30),
  address    VARCHAR(255),
  city       VARCHAR(80),
  telephone  VARCHAR(20)
);
CREATE INDEX owners_last_name ON owners (last_name);

CREATE TABLE pets (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR_IGNORECASE(30),
  birth_date DATE,
  type_id    INTEGER NOT NULL,
  owner_id   INTEGER
);
ALTER TABLE pets ADD CONSTRAINT fk_pets_owners FOREIGN KEY (owner_id) REFERENCES owners (id);
ALTER TABLE pets ADD CONSTRAINT fk_pets_types FOREIGN KEY (type_id) REFERENCES types (id);
ALTER TABLE pets ADD CONSTRAINT unique_owner_pet_name UNIQUE (owner_id, name);
CREATE INDEX pets_name ON pets (name);

CREATE TABLE visits (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pet_id      INTEGER,
  visit_date  DATE,
  description VARCHAR(255)
);
ALTER TABLE visits ADD CONSTRAINT fk_visits_pets FOREIGN KEY (pet_id) REFERENCES pets (id);
CREATE INDEX visits_pet_id ON visits (pet_id);

CREATE TABLE app_user (
  id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username             VARCHAR_IGNORECASE(100) NOT NULL UNIQUE,
  password_hash        VARCHAR(255) NOT NULL,
  role                 VARCHAR(20) NOT NULL,
  enabled              BOOLEAN NOT NULL DEFAULT TRUE,
  must_change_password BOOLEAN NOT NULL DEFAULT FALSE,
  owner_id             INTEGER
);
ALTER TABLE app_user ADD CONSTRAINT fk_app_user_owners FOREIGN KEY (owner_id) REFERENCES owners (id);

CREATE TABLE clinic_settings (
  id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  grid_granularity_min INTEGER NOT NULL DEFAULT 15,
  hold_duration_min    INTEGER NOT NULL DEFAULT 10,
  booking_horizon_days INTEGER NOT NULL DEFAULT 60,
  min_visit_min        INTEGER NOT NULL DEFAULT 15,
  max_visit_min        INTEGER NOT NULL DEFAULT 120,
  default_visit_min    INTEGER NOT NULL DEFAULT 30,
  zone_id              VARCHAR(50) NOT NULL DEFAULT 'Europe/Amsterdam',
  morning_start        TIME NOT NULL DEFAULT '08:00:00',
  morning_end          TIME NOT NULL DEFAULT '12:00:00',
  afternoon_start      TIME NOT NULL DEFAULT '12:00:00',
  afternoon_end        TIME NOT NULL DEFAULT '17:00:00',
  evening_start        TIME NOT NULL DEFAULT '17:00:00',
  evening_end          TIME NOT NULL DEFAULT '20:00:00'
);

CREATE TABLE vet_weekly_shift (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vet_id      INTEGER NOT NULL,
  day_of_week INTEGER NOT NULL,
  start_local TIME NOT NULL,
  end_local   TIME NOT NULL
);
ALTER TABLE vet_weekly_shift ADD CONSTRAINT fk_vet_weekly_shift_vets FOREIGN KEY (vet_id) REFERENCES vets (id);
CREATE INDEX vet_weekly_shift_vet_id ON vet_weekly_shift (vet_id);

CREATE TABLE vet_availability_exception (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vet_id      INTEGER NOT NULL,
  date        DATE NOT NULL,
  type        VARCHAR(20) NOT NULL,
  start_local TIME,
  end_local   TIME
);
ALTER TABLE vet_availability_exception ADD CONSTRAINT fk_vet_avail_exc_vets FOREIGN KEY (vet_id) REFERENCES vets (id);
CREATE INDEX vet_avail_exc_vet_date ON vet_availability_exception (vet_id, date);

CREATE TABLE vet_leave (
  id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vet_id    INTEGER NOT NULL,
  from_date DATE NOT NULL,
  to_date   DATE NOT NULL
);
ALTER TABLE vet_leave ADD CONSTRAINT fk_vet_leave_vets FOREIGN KEY (vet_id) REFERENCES vets (id);
CREATE INDEX vet_leave_vet_id ON vet_leave (vet_id);

CREATE TABLE clinic_closure (
  id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_date DATE NOT NULL,
  to_date   DATE NOT NULL
);
CREATE INDEX clinic_closure_dates ON clinic_closure (from_date, to_date);

CREATE TABLE appointment_request (
  id                       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id                 INTEGER NOT NULL,
  pet_id                   INTEGER NOT NULL,
  free_text                CLOB,
  status                   VARCHAR(30) NOT NULL,
  consent_flag             BOOLEAN NOT NULL DEFAULT FALSE,
  consent_at               TIMESTAMP,
  consent_text_snapshot    CLOB,
  interpretation_json      CLOB,
  resulting_appointment_id INTEGER,
  active_hold_id           INTEGER
);
ALTER TABLE appointment_request ADD CONSTRAINT fk_app_req_owners FOREIGN KEY (owner_id) REFERENCES owners (id);
ALTER TABLE appointment_request ADD CONSTRAINT fk_app_req_pets FOREIGN KEY (pet_id) REFERENCES pets (id);
CREATE INDEX app_req_owner_id ON appointment_request (owner_id);
CREATE INDEX app_req_pet_id ON appointment_request (pet_id);
CREATE INDEX app_req_status ON appointment_request (status);

CREATE TABLE appointment (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id    INTEGER,
  pet_id        INTEGER NOT NULL,
  vet_id        INTEGER NOT NULL,
  start_instant TIMESTAMP NOT NULL,
  duration_min  INTEGER NOT NULL,
  status        VARCHAR(30) NOT NULL,
  reason        VARCHAR(500)
);
ALTER TABLE appointment ADD CONSTRAINT fk_appointment_request FOREIGN KEY (request_id) REFERENCES appointment_request (id);
ALTER TABLE appointment ADD CONSTRAINT fk_appointment_pets FOREIGN KEY (pet_id) REFERENCES pets (id);
ALTER TABLE appointment ADD CONSTRAINT fk_appointment_vets FOREIGN KEY (vet_id) REFERENCES vets (id);
CREATE INDEX appointment_pet_id ON appointment (pet_id);
CREATE INDEX appointment_vet_id ON appointment (vet_id);
CREATE INDEX appointment_start_instant ON appointment (start_instant);

CREATE TABLE slot_hold (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vet_id        INTEGER NOT NULL,
  start_instant TIMESTAMP NOT NULL,
  request_id    INTEGER NOT NULL,
  expires_at    TIMESTAMP NOT NULL,
  CONSTRAINT uk_slot_hold_vet_start UNIQUE (vet_id, start_instant)
);
ALTER TABLE slot_hold ADD CONSTRAINT fk_slot_hold_vets FOREIGN KEY (vet_id) REFERENCES vets (id);
ALTER TABLE slot_hold ADD CONSTRAINT fk_slot_hold_request FOREIGN KEY (request_id) REFERENCES appointment_request (id);
CREATE INDEX slot_hold_expires_at ON slot_hold (expires_at);

CREATE TABLE rejected_suggestion (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id    INTEGER NOT NULL,
  vet_id        INTEGER NOT NULL,
  start_instant TIMESTAMP NOT NULL
);
ALTER TABLE rejected_suggestion ADD CONSTRAINT fk_rej_sug_request FOREIGN KEY (request_id) REFERENCES appointment_request (id);
ALTER TABLE rejected_suggestion ADD CONSTRAINT fk_rej_sug_vets FOREIGN KEY (vet_id) REFERENCES vets (id);
CREATE INDEX rej_sug_request_id ON rejected_suggestion (request_id);

ALTER TABLE appointment_request ADD CONSTRAINT fk_app_req_resulting_app FOREIGN KEY (resulting_appointment_id) REFERENCES appointment (id);
ALTER TABLE appointment_request ADD CONSTRAINT fk_app_req_active_hold FOREIGN KEY (active_hold_id) REFERENCES slot_hold (id);

-- Seed Data
INSERT INTO vets VALUES (default, 'James', 'Carter');
INSERT INTO vets VALUES (default, 'Helen', 'Leary');
INSERT INTO vets VALUES (default, 'Linda', 'Douglas');
INSERT INTO vets VALUES (default, 'Rafael', 'Ortega');
INSERT INTO vets VALUES (default, 'Henry', 'Stevens');
INSERT INTO vets VALUES (default, 'Sharon', 'Jenkins');

INSERT INTO specialties VALUES (default, 'radiology');
INSERT INTO specialties VALUES (default, 'surgery');
INSERT INTO specialties VALUES (default, 'dentistry');

INSERT INTO vet_specialties VALUES (2, 1);
INSERT INTO vet_specialties VALUES (3, 2);
INSERT INTO vet_specialties VALUES (3, 3);
INSERT INTO vet_specialties VALUES (4, 2);
INSERT INTO vet_specialties VALUES (5, 1);

INSERT INTO types VALUES (default, 'cat');
INSERT INTO types VALUES (default, 'dog');
INSERT INTO types VALUES (default, 'lizard');
INSERT INTO types VALUES (default, 'snake');
INSERT INTO types VALUES (default, 'bird');
INSERT INTO types VALUES (default, 'hamster');

INSERT INTO owners VALUES (default, 'George', 'Franklin', '110 W. Liberty St.', 'Madison', '6085551023');
INSERT INTO owners VALUES (default, 'Betty', 'Davis', '638 Cardinal Ave.', 'Sun Prairie', '6085551749');
INSERT INTO owners VALUES (default, 'Eduardo', 'Rodriquez', '2693 Commerce St.', 'McFarland', '6085558763');
INSERT INTO owners VALUES (default, 'Harold', 'Davis', '563 Friendly St.', 'Windsor', '6085553198');
INSERT INTO owners VALUES (default, 'Peter', 'McTavish', '2387 S. Fair Way', 'Madison', '6085552765');
INSERT INTO owners VALUES (default, 'Jean', 'Coleman', '105 N. Lake St.', 'Monona', '6085552654');
INSERT INTO owners VALUES (default, 'Jeff', 'Black', '1450 Oak Blvd.', 'Monona', '6085555387');
INSERT INTO owners VALUES (default, 'Maria', 'Escobito', '345 Maple St.', 'Madison', '6085557683');
INSERT INTO owners VALUES (default, 'David', 'Schroeder', '2749 Blackhawk Trail', 'Madison', '6085559435');
INSERT INTO owners VALUES (default, 'Carlos', 'Estaban', '2335 Independence La.', 'Waunakee', '6085555487');

INSERT INTO pets VALUES (default, 'Leo', '2010-09-07', 1, 1);
INSERT INTO pets VALUES (default, 'Basil', '2012-08-06', 6, 2);
INSERT INTO pets VALUES (default, 'Rosy', '2011-04-17', 2, 3);
INSERT INTO pets VALUES (default, 'Jewel', '2010-03-07', 2, 3);
INSERT INTO pets VALUES (default, 'Iggy', '2010-11-30', 3, 4);
INSERT INTO pets VALUES (default, 'George', '2010-01-20', 4, 5);
INSERT INTO pets VALUES (default, 'Samantha', '2012-09-04', 1, 6);
INSERT INTO pets VALUES (default, 'Max', '2012-09-04', 1, 6);
INSERT INTO pets VALUES (default, 'Lucky', '2011-08-06', 5, 7);
INSERT INTO pets VALUES (default, 'Mulligan', '2007-02-24', 2, 8);
INSERT INTO pets VALUES (default, 'Freddy', '2010-03-09', 5, 9);
INSERT INTO pets VALUES (default, 'Lucky', '2010-06-24', 2, 10);
INSERT INTO pets VALUES (default, 'Sly', '2012-06-08', 1, 10);

INSERT INTO visits VALUES (default, 7, '2013-01-01', 'rabies shot');
INSERT INTO visits VALUES (default, 8, '2013-01-02', 'rabies shot');
INSERT INTO visits VALUES (default, 8, '2013-01-03', 'neutered');
INSERT INTO visits VALUES (default, 7, '2013-01-04', 'spayed');

INSERT INTO clinic_settings (id, grid_granularity_min, hold_duration_min, booking_horizon_days, min_visit_min, max_visit_min, default_visit_min, zone_id, morning_start, morning_end, afternoon_start, afternoon_end, evening_start, evening_end)
VALUES (default, 15, 10, 60, 15, 120, 30, 'Europe/Amsterdam', '08:00:00', '12:00:00', '12:00:00', '17:00:00', '17:00:00', '20:00:00');
