CREATE TABLE IF NOT EXISTS vets (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name TEXT,
  last_name  TEXT
);
CREATE INDEX IF NOT EXISTS idx_vets_last_name ON vets (last_name);

CREATE TABLE IF NOT EXISTS specialties (
  id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT
);
CREATE INDEX IF NOT EXISTS idx_specialties_name ON specialties (name);

CREATE TABLE IF NOT EXISTS vet_specialties (
  vet_id       INT NOT NULL REFERENCES vets (id),
  specialty_id INT NOT NULL REFERENCES specialties (id),
  UNIQUE (vet_id, specialty_id)
);

CREATE TABLE IF NOT EXISTS types (
  id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT
);
CREATE INDEX IF NOT EXISTS idx_types_name ON types (name);

CREATE TABLE IF NOT EXISTS owners (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name TEXT,
  last_name  TEXT,
  address    TEXT,
  city       TEXT,
  telephone  TEXT
);
CREATE INDEX IF NOT EXISTS idx_owners_last_name ON owners (last_name);

CREATE TABLE IF NOT EXISTS pets (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       TEXT,
  birth_date DATE,
  type_id    INT NOT NULL REFERENCES types (id),
  owner_id   INT REFERENCES owners (id)
);
CREATE INDEX IF NOT EXISTS idx_pets_name ON pets (name);
CREATE INDEX IF NOT EXISTS idx_pets_owner_id ON pets (owner_id);
CREATE UNIQUE INDEX IF NOT EXISTS unique_owner_pet_name ON pets (owner_id, LOWER(name));

CREATE TABLE IF NOT EXISTS visits (
  id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pet_id      INT REFERENCES pets (id),
  visit_date  DATE,
  description TEXT
);
CREATE INDEX IF NOT EXISTS idx_visits_pet_id ON visits (pet_id);

CREATE TABLE IF NOT EXISTS app_user (
  id                   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username             TEXT NOT NULL,
  password_hash        TEXT NOT NULL,
  role                 TEXT NOT NULL,
  enabled              BOOLEAN NOT NULL DEFAULT TRUE,
  must_change_password BOOLEAN NOT NULL DEFAULT FALSE,
  owner_id             INT REFERENCES owners (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_app_user_username ON app_user (LOWER(username));
CREATE INDEX IF NOT EXISTS idx_app_user_owner_id ON app_user (owner_id);

CREATE TABLE IF NOT EXISTS clinic_settings (
  id                   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  grid_granularity_min INT NOT NULL DEFAULT 15,
  hold_duration_min    INT NOT NULL DEFAULT 10,
  booking_horizon_days INT NOT NULL DEFAULT 60,
  min_visit_min        INT NOT NULL DEFAULT 15,
  max_visit_min        INT NOT NULL DEFAULT 120,
  default_visit_min    INT NOT NULL DEFAULT 30,
  zone_id              TEXT NOT NULL DEFAULT 'Europe/Amsterdam',
  morning_start        TIME NOT NULL DEFAULT '08:00:00',
  morning_end          TIME NOT NULL DEFAULT '12:00:00',
  afternoon_start      TIME NOT NULL DEFAULT '12:00:00',
  afternoon_end        TIME NOT NULL DEFAULT '17:00:00',
  evening_start        TIME NOT NULL DEFAULT '17:00:00',
  evening_end          TIME NOT NULL DEFAULT '20:00:00'
);

CREATE TABLE IF NOT EXISTS vet_weekly_shift (
  id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vet_id      INT NOT NULL REFERENCES vets (id),
  day_of_week INT NOT NULL,
  start_local TIME NOT NULL,
  end_local   TIME NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_vet_weekly_shift_vet_id ON vet_weekly_shift (vet_id);

CREATE TABLE IF NOT EXISTS vet_availability_exception (
  id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vet_id      INT NOT NULL REFERENCES vets (id),
  date        DATE NOT NULL,
  type        TEXT NOT NULL,
  start_local TIME,
  end_local   TIME
);
CREATE INDEX IF NOT EXISTS idx_vet_avail_exc_vet_date ON vet_availability_exception (vet_id, date);

CREATE TABLE IF NOT EXISTS vet_leave (
  id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vet_id    INT NOT NULL REFERENCES vets (id),
  from_date DATE NOT NULL,
  to_date   DATE NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_vet_leave_vet_id ON vet_leave (vet_id);

CREATE TABLE IF NOT EXISTS clinic_closure (
  id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_date DATE NOT NULL,
  to_date   DATE NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_clinic_closure_dates ON clinic_closure (from_date, to_date);

CREATE TABLE IF NOT EXISTS appointment_request (
  id                       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id                 INT NOT NULL REFERENCES owners (id),
  pet_id                   INT NOT NULL REFERENCES pets (id),
  free_text                TEXT,
  status                   TEXT NOT NULL,
  consent_flag             BOOLEAN NOT NULL DEFAULT FALSE,
  consent_at               TIMESTAMP WITH TIME ZONE,
  consent_text_snapshot    TEXT,
  interpretation_json      TEXT,
  resulting_appointment_id INT,
  active_hold_id           INT
);
CREATE INDEX IF NOT EXISTS idx_appointment_request_owner_id ON appointment_request (owner_id);
CREATE INDEX IF NOT EXISTS idx_appointment_request_pet_id ON appointment_request (pet_id);
CREATE INDEX IF NOT EXISTS idx_appointment_request_status ON appointment_request (status);

CREATE TABLE IF NOT EXISTS appointment (
  id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id    INT REFERENCES appointment_request (id),
  pet_id        INT NOT NULL REFERENCES pets (id),
  vet_id        INT NOT NULL REFERENCES vets (id),
  start_instant TIMESTAMP WITH TIME ZONE NOT NULL,
  duration_min  INT NOT NULL,
  status        TEXT NOT NULL,
  reason        TEXT
);
CREATE INDEX IF NOT EXISTS idx_appointment_pet_id ON appointment (pet_id);
CREATE INDEX IF NOT EXISTS idx_appointment_vet_id ON appointment (vet_id);
CREATE INDEX IF NOT EXISTS idx_appointment_start_instant ON appointment (start_instant);

CREATE TABLE IF NOT EXISTS slot_hold (
  id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vet_id        INT NOT NULL REFERENCES vets (id),
  start_instant TIMESTAMP WITH TIME ZONE NOT NULL,
  request_id    INT NOT NULL REFERENCES appointment_request (id),
  expires_at    TIMESTAMP WITH TIME ZONE NOT NULL,
  UNIQUE (vet_id, start_instant)
);
CREATE INDEX IF NOT EXISTS idx_slot_hold_expires_at ON slot_hold (expires_at);

CREATE TABLE IF NOT EXISTS rejected_suggestion (
  id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id    INT NOT NULL REFERENCES appointment_request (id),
  vet_id        INT NOT NULL REFERENCES vets (id),
  start_instant TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_rejected_suggestion_request_id ON rejected_suggestion (request_id);

ALTER TABLE appointment_request ADD CONSTRAINT fk_app_req_resulting_app FOREIGN KEY (resulting_appointment_id) REFERENCES appointment (id);
ALTER TABLE appointment_request ADD CONSTRAINT fk_app_req_active_hold FOREIGN KEY (active_hold_id) REFERENCES slot_hold (id);

-- Seed Data
INSERT INTO vets (first_name, last_name) SELECT 'James', 'Carter' WHERE NOT EXISTS (SELECT * FROM vets WHERE id=1);
INSERT INTO vets (first_name, last_name) SELECT 'Helen', 'Leary' WHERE NOT EXISTS (SELECT * FROM vets WHERE id=2);
INSERT INTO vets (first_name, last_name) SELECT 'Linda', 'Douglas' WHERE NOT EXISTS (SELECT * FROM vets WHERE id=3);
INSERT INTO vets (first_name, last_name) SELECT 'Rafael', 'Ortega' WHERE NOT EXISTS (SELECT * FROM vets WHERE id=4);
INSERT INTO vets (first_name, last_name) SELECT 'Henry', 'Stevens' WHERE NOT EXISTS (SELECT * FROM vets WHERE id=5);
INSERT INTO vets (first_name, last_name) SELECT 'Sharon', 'Jenkins' WHERE NOT EXISTS (SELECT * FROM vets WHERE id=6);

INSERT INTO specialties (name) SELECT 'radiology' WHERE NOT EXISTS (SELECT * FROM specialties WHERE name='radiology');
INSERT INTO specialties (name) SELECT 'surgery' WHERE NOT EXISTS (SELECT * FROM specialties WHERE name='surgery'); 
INSERT INTO specialties (name) SELECT 'dentistry' WHERE NOT EXISTS (SELECT * FROM specialties WHERE name='dentistry');

INSERT INTO vet_specialties VALUES (2, 1) ON CONFLICT (vet_id, specialty_id) DO NOTHING;
INSERT INTO vet_specialties VALUES (3, 2) ON CONFLICT (vet_id, specialty_id) DO NOTHING;
INSERT INTO vet_specialties VALUES (3, 3) ON CONFLICT (vet_id, specialty_id) DO NOTHING;
INSERT INTO vet_specialties VALUES (4, 2) ON CONFLICT (vet_id, specialty_id) DO NOTHING;
INSERT INTO vet_specialties VALUES (5, 1) ON CONFLICT (vet_id, specialty_id) DO NOTHING;

INSERT INTO types (name) SELECT 'cat' WHERE NOT EXISTS (SELECT * FROM types WHERE name='cat');
INSERT INTO types (name) SELECT 'dog' WHERE NOT EXISTS (SELECT * FROM types WHERE name='dog');
INSERT INTO types (name) SELECT 'lizard' WHERE NOT EXISTS (SELECT * FROM types WHERE name='lizard');
INSERT INTO types (name) SELECT 'snake' WHERE NOT EXISTS (SELECT * FROM types WHERE name='snake');
INSERT INTO types (name) SELECT 'bird' WHERE NOT EXISTS (SELECT * FROM types WHERE name='bird');
INSERT INTO types (name) SELECT 'hamster' WHERE NOT EXISTS (SELECT * FROM types WHERE name='hamster');

INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'George', 'Franklin', '110 W. Liberty St.', 'Madison', '6085551023' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=1);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Betty', 'Davis', '638 Cardinal Ave.', 'Sun Prairie', '6085551749' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=2);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Eduardo', 'Rodriquez', '2693 Commerce St.', 'McFarland', '6085558763' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=3);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Harold', 'Davis', '563 Friendly St.', 'Windsor', '6085553198' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=4);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Peter', 'McTavish', '2387 S. Fair Way', 'Madison', '6085552765' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=5);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Jean', 'Coleman', '105 N. Lake St.', 'Monona', '6085552654' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=6);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Jeff', 'Black', '1450 Oak Blvd.', 'Monona', '6085555387' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=7);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Maria', 'Escobito', '345 Maple St.', 'Madison', '6085557683' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=8);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'David', 'Schroeder', '2749 Blackhawk Trail', 'Madison', '6085559435' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=9);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Carlos', 'Estaban', '2335 Independence La.', 'Waunakee', '6085555487' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=10);

INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Leo', '2000-09-07', 1, 1 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=1);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Basil', '2002-08-06', 6, 2 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=2);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Rosy', '2001-04-17', 2, 3 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=3);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Jewel', '2000-03-07', 2, 3 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=4);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Iggy', '2000-11-30', 3, 4 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=5);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'George', '2000-01-20', 4, 5 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=6);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Samantha', '1995-09-04', 1, 6 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=7);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Max', '1995-09-04', 1, 6 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=8);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Lucky', '1999-08-06', 5, 7 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=9);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Mulligan', '1997-02-24', 2, 8 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=10);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Freddy', '2000-03-09', 5, 9 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=11);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Lucky', '2000-06-24', 2, 10 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=12);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Sly', '2002-06-08', 1, 10 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=13);

INSERT INTO visits (pet_id, visit_date, description) SELECT 7, '2010-03-04', 'rabies shot' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=1);
INSERT INTO visits (pet_id, visit_date, description) SELECT 8, '2011-03-04', 'rabies shot' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=2);
INSERT INTO visits (pet_id, visit_date, description) SELECT 8, '2009-06-04', 'neutered' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=3);
INSERT INTO visits (pet_id, visit_date, description) SELECT 7, '2008-09-04', 'spayed' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=4);

INSERT INTO clinic_settings (id, grid_granularity_min, hold_duration_min, booking_horizon_days, min_visit_min, max_visit_min, default_visit_min, zone_id, morning_start, morning_end, afternoon_start, afternoon_end, evening_start, evening_end)
SELECT 1, 15, 10, 60, 15, 120, 30, 'Europe/Amsterdam', '08:00:00', '12:00:00', '12:00:00', '17:00:00', '17:00:00', '20:00:00'
WHERE NOT EXISTS (SELECT * FROM clinic_settings WHERE id=1);
