CREATE TABLE scheduling_requests (
  id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version              INTEGER NOT NULL DEFAULT 0,
  owner_id             INTEGER NOT NULL,
  pet_id               INTEGER NOT NULL,
  state                VARCHAR(30) NOT NULL,
  queue_reason         VARCHAR(50),
  raw_text             TEXT,
  interpretation_json  TEXT,
  ai_consent           BOOLEAN NOT NULL DEFAULT FALSE,
  preferred_date_start DATE,
  preferred_date_end   DATE,
  active_pet_key       INTEGER,
  created_at           TIMESTAMP,
  updated_at           TIMESTAMP,
  queued_at            TIMESTAMP,
  CONSTRAINT fk_scheduling_requests_owners FOREIGN KEY (owner_id) REFERENCES owners (id),
  CONSTRAINT fk_scheduling_requests_pets FOREIGN KEY (pet_id) REFERENCES pets (id),
  CONSTRAINT uk_scheduling_requests_active_pet UNIQUE (active_pet_key)
);
CREATE INDEX idx_scheduling_requests_state ON scheduling_requests (state);
CREATE INDEX idx_scheduling_requests_owner ON scheduling_requests (owner_id);
CREATE INDEX idx_scheduling_requests_pet ON scheduling_requests (pet_id);
