CREATE TABLE accounts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(80) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(16) NOT NULL,
  owner_id INTEGER UNIQUE,
  must_change_password BOOLEAN NOT NULL DEFAULT FALSE,
  temporary_password_expires_at TIMESTAMP WITH TIME ZONE,
  failed_sign_in_count INTEGER NOT NULL DEFAULT 0,
  locked_until TIMESTAMP WITH TIME ZONE,
  version BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT fk_accounts_owner FOREIGN KEY (owner_id) REFERENCES owners(id)
);

CREATE TABLE clinic_scheduling_settings (
  id INTEGER PRIMARY KEY,
  clinic_zone VARCHAR(64) NOT NULL,
  booking_horizon_days INTEGER NOT NULL,
  owner_minimum_notice_minutes INTEGER NOT NULL,
  offer_hold_minutes INTEGER NOT NULL,
  urgent_care_guidance VARCHAR(2000) NOT NULL,
  version BIGINT NOT NULL DEFAULT 0
);
INSERT INTO clinic_scheduling_settings VALUES
  (1, 'Europe/Amsterdam', 90, 120, 10, 'If your pet needs urgent care, contact the clinic or an emergency veterinarian immediately.', 0);

CREATE TABLE named_day_periods (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(80) NOT NULL UNIQUE,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  version BIGINT NOT NULL DEFAULT 0
);
CREATE TABLE recurring_vet_shifts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vet_id INTEGER NOT NULL,
  day_of_week INTEGER NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  version BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT fk_shift_vet FOREIGN KEY (vet_id) REFERENCES vets(id)
);
CREATE TABLE vet_availability_exceptions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vet_id INTEGER NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  available BOOLEAN NOT NULL,
  start_time TIME,
  end_time TIME,
  reason VARCHAR(255),
  version BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT fk_exception_vet FOREIGN KEY (vet_id) REFERENCES vets(id)
);
CREATE TABLE vet_leaves (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vet_id INTEGER NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  reason VARCHAR(255),
  version BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT fk_leave_vet FOREIGN KEY (vet_id) REFERENCES vets(id)
);
CREATE TABLE clinic_closures (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  reason VARCHAR(255),
  version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE scheduling_requests (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pet_id INTEGER NOT NULL,
  state VARCHAR(32) NOT NULL,
  current_revision_id INTEGER,
  emergency_priority BOOLEAN NOT NULL DEFAULT FALSE,
  version BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT fk_request_pet FOREIGN KEY (pet_id) REFERENCES pets(id)
);
CREATE UNIQUE INDEX unique_active_request_per_pet ON scheduling_requests(pet_id, state);
CREATE TABLE request_revisions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id INTEGER NOT NULL,
  revision_number INTEGER NOT NULL,
  source_text VARCHAR(2000) NOT NULL,
  consent_given BOOLEAN NOT NULL,
  consent_at TIMESTAMP WITH TIME ZONE,
  raw_interpretation VARCHAR(4000),
  model_identifier VARCHAR(255),
  correlation_id VARCHAR(80) NOT NULL,
  visit_reason VARCHAR(1000),
  duration_minutes INTEGER,
  care_type VARCHAR(80),
  required_specialty VARCHAR(80),
  preferred_vet_id INTEGER,
  urgency VARCHAR(32),
  confirmed_at TIMESTAMP WITH TIME ZONE,
  status VARCHAR(32) NOT NULL,
  version BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT unique_request_revision UNIQUE (request_id, revision_number),
  CONSTRAINT fk_revision_request FOREIGN KEY (request_id) REFERENCES scheduling_requests(id),
  CONSTRAINT fk_revision_vet FOREIGN KEY (preferred_vet_id) REFERENCES vets(id)
);
ALTER TABLE scheduling_requests ADD CONSTRAINT fk_request_revision FOREIGN KEY (current_revision_id) REFERENCES request_revisions(id);
CREATE TABLE request_availability_windows (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  revision_id INTEGER NOT NULL,
  kind VARCHAR(16) NOT NULL,
  applicable_date DATE,
  day_of_week INTEGER,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  source VARCHAR(32) NOT NULL,
  CONSTRAINT fk_window_revision FOREIGN KEY (revision_id) REFERENCES request_revisions(id)
);

CREATE TABLE appointment_offers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  revision_id INTEGER NOT NULL,
  vet_id INTEGER NOT NULL,
  start_at TIMESTAMP WITH TIME ZONE NOT NULL,
  duration_minutes INTEGER NOT NULL,
  offered_at TIMESTAMP WITH TIME ZONE NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  state VARCHAR(16) NOT NULL,
  rationale VARCHAR(1000) NOT NULL,
  rejection_reason VARCHAR(255),
  version BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT fk_offer_revision FOREIGN KEY (revision_id) REFERENCES request_revisions(id),
  CONSTRAINT fk_offer_vet FOREIGN KEY (vet_id) REFERENCES vets(id),
  CONSTRAINT unique_offer_slot_per_revision UNIQUE (revision_id, vet_id, start_at)
);
CREATE TABLE appointments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pet_id INTEGER NOT NULL,
  vet_id INTEGER NOT NULL,
  start_at TIMESTAMP WITH TIME ZONE NOT NULL,
  duration_minutes INTEGER NOT NULL,
  source VARCHAR(32) NOT NULL,
  request_id INTEGER,
  revision_id INTEGER,
  offer_id INTEGER UNIQUE,
  owner_agreement VARCHAR(1000),
  status VARCHAR(16) NOT NULL,
  change_reason VARCHAR(64),
  change_note VARCHAR(1000),
  version BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT fk_appointment_pet FOREIGN KEY (pet_id) REFERENCES pets(id),
  CONSTRAINT fk_appointment_vet FOREIGN KEY (vet_id) REFERENCES vets(id),
  CONSTRAINT fk_appointment_request FOREIGN KEY (request_id) REFERENCES scheduling_requests(id),
  CONSTRAINT fk_appointment_revision FOREIGN KEY (revision_id) REFERENCES request_revisions(id),
  CONSTRAINT fk_appointment_offer FOREIGN KEY (offer_id) REFERENCES appointment_offers(id)
);
CREATE TABLE reservation_blocks (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resource_type VARCHAR(16) NOT NULL,
  resource_id INTEGER NOT NULL,
  slot_start TIMESTAMP WITH TIME ZONE NOT NULL,
  owner_type VARCHAR(16) NOT NULL,
  owner_id INTEGER NOT NULL,
  state VARCHAR(16) NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE,
  CONSTRAINT unique_reservation_resource_slot UNIQUE (resource_type, resource_id, slot_start)
);

CREATE TABLE staff_queue_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id INTEGER NOT NULL UNIQUE,
  state VARCHAR(32) NOT NULL,
  priority VARCHAR(16) NOT NULL,
  claimed_by_account_id INTEGER,
  resolution_details VARCHAR(1000),
  version BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT fk_queue_request FOREIGN KEY (request_id) REFERENCES scheduling_requests(id),
  CONSTRAINT fk_queue_account FOREIGN KEY (claimed_by_account_id) REFERENCES accounts(id)
);
CREATE TABLE scheduling_audit_records (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
  correlation_id VARCHAR(80),
  actor_account_id INTEGER,
  actor VARCHAR(80) NOT NULL,
  action VARCHAR(64) NOT NULL,
  target_type VARCHAR(64) NOT NULL,
  target_id VARCHAR(80) NOT NULL,
  prior_value VARCHAR(2000),
  resulting_value VARCHAR(2000),
  reason VARCHAR(1000)
);
ALTER TABLE visits ADD appointment_id INTEGER UNIQUE;
ALTER TABLE visits ADD vet_id INTEGER;
ALTER TABLE visits ADD completed_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE visits ADD clinical_notes VARCHAR(2000);
ALTER TABLE visits ADD CONSTRAINT fk_visit_appointment FOREIGN KEY (appointment_id) REFERENCES appointments(id);
ALTER TABLE visits ADD CONSTRAINT fk_visit_vet FOREIGN KEY (vet_id) REFERENCES vets(id);
