CREATE TABLE slot_occupancy (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vet_id         INTEGER NOT NULL,
  start_time     TIMESTAMP NOT NULL,
  end_time       TIMESTAMP NOT NULL,
  occupancy_type VARCHAR(20) NOT NULL,
  reference_id   INTEGER,
  created_at     TIMESTAMP,
  CONSTRAINT uk_slot_occupancy_vet_start UNIQUE (vet_id, start_time),
  CONSTRAINT fk_slot_occupancy_vets FOREIGN KEY (vet_id) REFERENCES vets (id)
);
CREATE INDEX idx_slot_occupancy_vet_time ON slot_occupancy (vet_id, start_time);

CREATE TABLE holds (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version      INTEGER NOT NULL DEFAULT 0,
  request_id   INTEGER NOT NULL,
  vet_id       INTEGER NOT NULL,
  start_time   TIMESTAMP NOT NULL,
  end_time     TIMESTAMP NOT NULL,
  expires_at   TIMESTAMP NOT NULL,
  status       VARCHAR(20) NOT NULL,
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT fk_holds_scheduling_requests FOREIGN KEY (request_id) REFERENCES scheduling_requests (id),
  CONSTRAINT fk_holds_vets FOREIGN KEY (vet_id) REFERENCES vets (id)
);
CREATE INDEX idx_holds_request ON holds (request_id);
CREATE INDEX idx_holds_status_expires ON holds (status, expires_at);

CREATE TABLE appointments (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version      INTEGER NOT NULL DEFAULT 0,
  owner_id     INTEGER NOT NULL,
  pet_id       INTEGER NOT NULL,
  vet_id       INTEGER NOT NULL,
  request_id   INTEGER,
  start_time   TIMESTAMP NOT NULL,
  end_time     TIMESTAMP NOT NULL,
  status       VARCHAR(30) NOT NULL,
  reason       VARCHAR(255),
  created_at   TIMESTAMP,
  updated_at   TIMESTAMP,
  CONSTRAINT fk_appointments_owners FOREIGN KEY (owner_id) REFERENCES owners (id),
  CONSTRAINT fk_appointments_pets FOREIGN KEY (pet_id) REFERENCES pets (id),
  CONSTRAINT fk_appointments_vets FOREIGN KEY (vet_id) REFERENCES vets (id),
  CONSTRAINT fk_appointments_requests FOREIGN KEY (request_id) REFERENCES scheduling_requests (id)
);
CREATE INDEX idx_appointments_owner ON appointments (owner_id);
CREATE INDEX idx_appointments_pet ON appointments (pet_id);
CREATE INDEX idx_appointments_vet_time ON appointments (vet_id, start_time);
