CREATE TABLE user_account (
  id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username             VARCHAR(100) NOT NULL,
  password             VARCHAR(255) NOT NULL,
  role                 VARCHAR(20) NOT NULL,
  must_change_password BOOLEAN NOT NULL DEFAULT FALSE,
  owner_id             INTEGER,
  CONSTRAINT uk_user_account_username UNIQUE (username),
  CONSTRAINT fk_user_account_owners FOREIGN KEY (owner_id) REFERENCES owners (id)
);
CREATE INDEX idx_user_account_username ON user_account (username);
CREATE INDEX idx_user_account_owner ON user_account (owner_id);
