CREATE TABLE request_exclusions (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id INTEGER NOT NULL,
  vet_id     INTEGER NOT NULL,
  start_time TIMESTAMP NOT NULL,
  created_at TIMESTAMP,
  CONSTRAINT fk_request_exclusions_requests FOREIGN KEY (request_id) REFERENCES scheduling_requests (id),
  CONSTRAINT fk_request_exclusions_vets FOREIGN KEY (vet_id) REFERENCES vets (id)
);
CREATE INDEX idx_request_exclusions_request ON request_exclusions (request_id);
