CREATE TABLE scheduling_requests (
  id                        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pet_id                    INTEGER NOT NULL,
  active_pet_id             INTEGER,
  request_text              VARCHAR(2000) NOT NULL,
  state                     VARCHAR(32) NOT NULL,
  with_staff_reason         VARCHAR(32),
  staff_reason              VARCHAR(255),
  failure_count             INTEGER NOT NULL DEFAULT 0,
  current_interpretation_id INTEGER,
  created_date              DATE NOT NULL,
  created_time              TIME NOT NULL,
  updated_date              DATE,
  updated_time              TIME,
  version                   BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT fk_scheduling_requests_pet FOREIGN KEY (pet_id) REFERENCES pets (id),
  CONSTRAINT fk_scheduling_requests_active_pet FOREIGN KEY (active_pet_id) REFERENCES pets (id),
  CONSTRAINT uq_scheduling_requests_active_pet UNIQUE (active_pet_id),
  CONSTRAINT ck_scheduling_requests_state CHECK (state IN (
    'AWAITING_CONSENT', 'INTERPRETING', 'INTERPRETATION_FAILED', 'INTERPRETED',
    'SUGGESTION_OFFERED', 'WITH_STAFF', 'ACCEPTED', 'ABANDONED'
  )),
  CONSTRAINT ck_scheduling_requests_reason CHECK (with_staff_reason IS NULL OR with_staff_reason IN (
    'DECLINED_CONSENT', 'AI_UNAVAILABLE', 'UNMATCHED_SPECIALTY', 'NO_SLOTS',
    'HOLD_RELEASED', 'SCHEDULE_CHANGED', 'STAFF_CREATED', 'OWNER_CHOICE'
  ))
);
CREATE INDEX scheduling_requests_pet_id ON scheduling_requests (pet_id);
CREATE INDEX scheduling_requests_state ON scheduling_requests (state);

CREATE TABLE interpretations (
  id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id          INTEGER NOT NULL,
  understood          BOOLEAN NOT NULL,
  care_type           VARCHAR(16),
  specialty           VARCHAR(80),
  specialty_label     VARCHAR(255),
  duration_minutes    INTEGER,
  preferred_vet_id    INTEGER,
  origin              VARCHAR(16) NOT NULL,
  raw_json             CLOB,
  model_tag            VARCHAR(120),
  prompt_version       VARCHAR(80),
  created_date         DATE NOT NULL,
  created_time         TIME NOT NULL,
  CONSTRAINT fk_interpretations_request FOREIGN KEY (request_id) REFERENCES scheduling_requests (id),
  CONSTRAINT fk_interpretations_preferred_vet FOREIGN KEY (preferred_vet_id) REFERENCES vets (id),
  CONSTRAINT ck_interpretations_care_type CHECK (care_type IS NULL OR care_type IN ('GENERAL', 'SPECIALTY')),
  CONSTRAINT ck_interpretations_specialty CHECK (specialty IS NULL OR specialty IN (
    'radiology', 'surgery', 'dentistry', 'OTHER'
  )),
  CONSTRAINT ck_interpretations_origin CHECK (origin IN ('AI', 'STAFF'))
);
CREATE INDEX interpretations_request_id ON interpretations (request_id);

ALTER TABLE scheduling_requests ADD CONSTRAINT fk_scheduling_requests_current_interpretation
  FOREIGN KEY (current_interpretation_id) REFERENCES interpretations (id);

CREATE TABLE interpretation_windows (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  interpretation_id INTEGER NOT NULL,
  window_kind       VARCHAR(16) NOT NULL,
  weekday           VARCHAR(16),
  window_date       DATE,
  start_time        TIME NOT NULL,
  end_time          TIME NOT NULL,
  CONSTRAINT fk_interpretation_windows_interpretation FOREIGN KEY (interpretation_id) REFERENCES interpretations (id),
  CONSTRAINT ck_interpretation_windows_kind CHECK (window_kind IN ('PREFERRED', 'ALLOWED', 'EXCLUDED')),
  CONSTRAINT ck_interpretation_windows_selector CHECK (
    (weekday IS NOT NULL AND window_date IS NULL) OR (weekday IS NULL AND window_date IS NOT NULL)
  )
);
CREATE INDEX interpretation_windows_interpretation_id ON interpretation_windows (interpretation_id);

CREATE TABLE interpretation_failures (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id   INTEGER NOT NULL,
  failure_kind VARCHAR(32) NOT NULL,
  raw_output   CLOB,
  created_date DATE NOT NULL,
  created_time TIME NOT NULL,
  CONSTRAINT fk_interpretation_failures_request FOREIGN KEY (request_id) REFERENCES scheduling_requests (id),
  CONSTRAINT ck_interpretation_failures_kind CHECK (failure_kind IN (
    'UNPARSEABLE', 'ZERO_WINDOWS', 'NOT_UNDERSTOOD'
  ))
);
CREATE INDEX interpretation_failures_request_id ON interpretation_failures (request_id);

CREATE TABLE request_rejections (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id       INTEGER NOT NULL,
  vet_id           INTEGER NOT NULL,
  appointment_date DATE NOT NULL,
  start_time       TIME NOT NULL,
  CONSTRAINT fk_request_rejections_request FOREIGN KEY (request_id) REFERENCES scheduling_requests (id),
  CONSTRAINT fk_request_rejections_vet FOREIGN KEY (vet_id) REFERENCES vets (id),
  CONSTRAINT uq_request_rejections_slot UNIQUE (request_id, vet_id, appointment_date, start_time)
);

CREATE TABLE appointments (
  id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id         INTEGER,
  pet_id             INTEGER NOT NULL,
  vet_id             INTEGER NOT NULL,
  appointment_date   DATE NOT NULL,
  start_time         TIME NOT NULL,
  end_time           TIME NOT NULL,
  status             VARCHAR(16) NOT NULL,
  held_date          DATE,
  held_time          TIME,
  rank_reason        VARCHAR(80),
  last_change_reason VARCHAR(255),
  last_changed_by    VARCHAR(80),
  cancelled_by       VARCHAR(16),
  cancelled_date     DATE,
  cancelled_time     TIME,
  created_date       DATE NOT NULL,
  created_time       TIME NOT NULL,
  CONSTRAINT fk_appointments_request FOREIGN KEY (request_id) REFERENCES scheduling_requests (id),
  CONSTRAINT fk_appointments_pet FOREIGN KEY (pet_id) REFERENCES pets (id),
  CONSTRAINT fk_appointments_vet FOREIGN KEY (vet_id) REFERENCES vets (id),
  CONSTRAINT uq_appointments_request UNIQUE (request_id),
  CONSTRAINT ck_appointments_status CHECK (status IN ('HELD', 'CONFIRMED', 'CANCELLED', 'COMPLETED', 'NO_SHOW')),
  CONSTRAINT ck_appointments_cancelled_by CHECK (cancelled_by IS NULL OR cancelled_by IN ('OWNER', 'STAFF')),
  CONSTRAINT ck_appointments_times CHECK (end_time > start_time),
  CONSTRAINT ck_appointments_hold_time CHECK (
    (status = 'HELD' AND held_date IS NOT NULL AND held_time IS NOT NULL)
    OR (status <> 'HELD')
  )
);
CREATE INDEX appointments_vet_slot ON appointments (vet_id, appointment_date, start_time, end_time, status);
CREATE INDEX appointments_pet_id ON appointments (pet_id);

ALTER TABLE visits ADD COLUMN appointment_id INTEGER;
ALTER TABLE visits ADD CONSTRAINT uq_visits_appointment UNIQUE (appointment_id);
ALTER TABLE visits ADD CONSTRAINT fk_visits_appointment FOREIGN KEY (appointment_id) REFERENCES appointments (id);

CREATE TABLE user_accounts (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username      VARCHAR(80) NOT NULL,
  password_hash VARCHAR(100) NOT NULL,
  role          VARCHAR(16) NOT NULL,
  owner_id      INTEGER,
  CONSTRAINT uq_user_accounts_username UNIQUE (username),
  CONSTRAINT uq_user_accounts_owner UNIQUE (owner_id),
  CONSTRAINT fk_user_accounts_owner FOREIGN KEY (owner_id) REFERENCES owners (id),
  CONSTRAINT ck_user_accounts_role CHECK (role IN ('OWNER', 'STAFF'))
);

CREATE TABLE clinic_settings (
  id                       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_horizon_days     INTEGER NOT NULL,
  minimum_lead_days        INTEGER NOT NULL,
  minimum_duration_minutes INTEGER NOT NULL,
  default_duration_minutes INTEGER NOT NULL,
  maximum_duration_minutes INTEGER NOT NULL,
  grid_minutes             INTEGER NOT NULL,
  morning_start            TIME NOT NULL,
  morning_end              TIME NOT NULL,
  afternoon_start          TIME NOT NULL,
  afternoon_end            TIME NOT NULL,
  evening_start            TIME NOT NULL,
  evening_end              TIME NOT NULL,
  time_zone                VARCHAR(80) NOT NULL
);

CREATE TABLE clinic_opening_hours (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  settings_id  INTEGER NOT NULL,
  weekday      VARCHAR(16) NOT NULL,
  open_time    TIME,
  close_time   TIME,
  CONSTRAINT fk_clinic_opening_hours_settings FOREIGN KEY (settings_id) REFERENCES clinic_settings (id),
  CONSTRAINT uq_clinic_opening_hours_weekday UNIQUE (settings_id, weekday),
  CONSTRAINT ck_clinic_opening_hours_values CHECK (
    (open_time IS NULL AND close_time IS NULL) OR (open_time IS NOT NULL AND close_time > open_time)
  )
);

CREATE TABLE vet_working_blocks (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vet_id     INTEGER NOT NULL,
  weekday    VARCHAR(16) NOT NULL,
  start_time TIME NOT NULL,
  end_time   TIME NOT NULL,
  CONSTRAINT fk_vet_working_blocks_vet FOREIGN KEY (vet_id) REFERENCES vets (id),
  CONSTRAINT ck_vet_working_blocks_times CHECK (end_time > start_time)
);
CREATE INDEX vet_working_blocks_vet_weekday ON vet_working_blocks (vet_id, weekday);

CREATE TABLE vet_exceptions (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vet_id         INTEGER NOT NULL,
  exception_date DATE NOT NULL,
  CONSTRAINT fk_vet_exceptions_vet FOREIGN KEY (vet_id) REFERENCES vets (id),
  CONSTRAINT uq_vet_exceptions_date UNIQUE (vet_id, exception_date)
);

CREATE TABLE vet_leave (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vet_id     INTEGER NOT NULL,
  start_date DATE NOT NULL,
  end_date   DATE NOT NULL,
  CONSTRAINT fk_vet_leave_vet FOREIGN KEY (vet_id) REFERENCES vets (id),
  CONSTRAINT ck_vet_leave_dates CHECK (end_date >= start_date)
);

CREATE TABLE clinic_closures (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  closure_date DATE NOT NULL,
  CONSTRAINT uq_clinic_closures_date UNIQUE (closure_date)
);
