CREATE TABLE accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(80) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(16) NOT NULL,
    owner_id INTEGER,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    temporary_password_expires_at TIMESTAMP WITH TIME ZONE,
    password_change_required BOOLEAN NOT NULL DEFAULT FALSE,
    session_version BIGINT NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_accounts_username UNIQUE (username),
    CONSTRAINT uq_accounts_owner UNIQUE (owner_id),
    CONSTRAINT fk_accounts_owner FOREIGN KEY (owner_id) REFERENCES owners(id),
    CONSTRAINT ck_accounts_role CHECK (role IN ('OWNER', 'STAFF')),
    CONSTRAINT ck_accounts_role_owner CHECK (
        (role = 'OWNER' AND owner_id IS NOT NULL) OR
        (role = 'STAFF' AND owner_id IS NULL)
    ),
    CONSTRAINT ck_accounts_temporary_password CHECK (
        (password_change_required AND temporary_password_expires_at IS NOT NULL) OR
        (NOT password_change_required AND temporary_password_expires_at IS NULL)
    )
);

CREATE TABLE protected_payloads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artifact_uuid UUID NOT NULL,
    artifact_type VARCHAR(80) NOT NULL,
    schema_version INTEGER NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    algorithm VARCHAR(32) NOT NULL CHECK (algorithm = 'AES-256-GCM'),
    nonce VARBINARY(12) NOT NULL,
    ciphertext BINARY LARGE OBJECT NOT NULL,
    authenticated_metadata BINARY LARGE OBJECT NOT NULL,
    active_envelope_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_protected_payload_artifact UNIQUE (artifact_uuid)
);

CREATE TABLE key_rotation_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_key_id VARCHAR(100),
    target_key_id VARCHAR(100) NOT NULL,
    state VARCHAR(24) NOT NULL CHECK (state IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED')),
    last_payload_id BIGINT,
    processed_count BIGINT NOT NULL DEFAULT 0,
    failure_count BIGINT NOT NULL DEFAULT 0,
    lease_token UUID,
    lease_until TIMESTAMP WITH TIME ZONE,
    started_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    failure_category VARCHAR(100),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE payload_key_envelopes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payload_id BIGINT NOT NULL,
    key_id VARCHAR(100) NOT NULL,
    wrapping_algorithm VARCHAR(32) NOT NULL CHECK (wrapping_algorithm = 'AES-256-GCM'),
    wrapping_nonce VARBINARY(12) NOT NULL,
    wrapped_key BINARY LARGE OBJECT NOT NULL,
    rotation_run_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_payload_key_envelope UNIQUE (payload_id, key_id),
    CONSTRAINT fk_envelope_payload FOREIGN KEY (payload_id) REFERENCES protected_payloads(id),
    CONSTRAINT fk_envelope_rotation FOREIGN KEY (rotation_run_id) REFERENCES key_rotation_runs(id)
);

ALTER TABLE protected_payloads ADD CONSTRAINT fk_payload_active_envelope
    FOREIGN KEY (active_envelope_id) REFERENCES payload_key_envelopes(id);
CREATE INDEX idx_payload_envelope_key ON payload_key_envelopes(key_id, payload_id);

CREATE TABLE command_records (
    id UUID PRIMARY KEY,
    actor_account_id BIGINT,
    action VARCHAR(100) NOT NULL,
    target VARCHAR(200) NOT NULL,
    request_hash VARCHAR(128) NOT NULL,
    status VARCHAR(16) NOT NULL CHECK (status IN ('ISSUED', 'COMPLETED')),
    result_status INTEGER,
    result_type VARCHAR(100),
    result_id VARCHAR(100),
    result_location VARCHAR(500),
    result_body VARCHAR(4000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_command_actor FOREIGN KEY (actor_account_id) REFERENCES accounts(id),
    CONSTRAINT ck_command_completion CHECK (
        (status = 'ISSUED' AND completed_at IS NULL) OR
        (status = 'COMPLETED' AND completed_at IS NOT NULL)
    )
);
CREATE INDEX idx_command_actor_action ON command_records(actor_account_id, action, target);

CREATE TABLE audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_account_id BIGINT,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    action VARCHAR(100) NOT NULL,
    target_type VARCHAR(100) NOT NULL,
    target_id VARCHAR(100) NOT NULL,
    outcome VARCHAR(50) NOT NULL,
    correlation_id UUID NOT NULL,
    command_id UUID,
    payload_id BIGINT,
    CONSTRAINT fk_audit_actor FOREIGN KEY (actor_account_id) REFERENCES accounts(id),
    CONSTRAINT fk_audit_command FOREIGN KEY (command_id) REFERENCES command_records(id),
    CONSTRAINT fk_audit_payload FOREIGN KEY (payload_id) REFERENCES protected_payloads(id)
);
CREATE INDEX idx_audit_target ON audit_events(target_type, target_id, occurred_at);
CREATE INDEX idx_audit_actor ON audit_events(actor_account_id, occurred_at);

CREATE TABLE owner_history_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id INTEGER NOT NULL,
    display_type VARCHAR(100) NOT NULL,
    summary VARCHAR(500) NOT NULL,
    target_type VARCHAR(100) NOT NULL,
    target_id VARCHAR(100) NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_history_owner FOREIGN KEY (owner_id) REFERENCES owners(id)
);
CREATE INDEX idx_history_owner ON owner_history_events(owner_id, occurred_at);

CREATE TABLE seed_versions (
    name VARCHAR(100) PRIMARY KEY,
    applied_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE calendar_state (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    revision BIGINT NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
INSERT INTO calendar_state(id, revision, version, updated_at) VALUES (1, 0, 0, CURRENT_TIMESTAMP);
