CREATE TABLE clinic_policy (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    zone_id VARCHAR(64) NOT NULL,
    booking_horizon_days INTEGER NOT NULL DEFAULT 90,
    hold_duration_minutes INTEGER NOT NULL DEFAULT 10,
    owner_notice_minutes INTEGER NOT NULL DEFAULT 120,
    start_grid_minutes INTEGER NOT NULL DEFAULT 15,
    clinic_phone VARCHAR(32) NOT NULL,
    contact_hours VARCHAR(255) NOT NULL,
    urgent_care_guidance TEXT NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE clinic_operating_intervals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_id INTEGER NOT NULL,
    weekday VARCHAR(16) NOT NULL,
    local_start TIME NOT NULL,
    local_end TIME NOT NULL,
    CONSTRAINT fk_operating_policy FOREIGN KEY (policy_id) REFERENCES clinic_policy(id)
);

CREATE TABLE clinic_allowed_durations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_id INTEGER NOT NULL,
    duration_minutes INTEGER NOT NULL,
    CONSTRAINT fk_durations_policy FOREIGN KEY (policy_id) REFERENCES clinic_policy(id),
    CONSTRAINT uq_allowed_duration UNIQUE (policy_id, duration_minutes)
);

CREATE TABLE clinic_named_periods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_id INTEGER NOT NULL,
    name VARCHAR(64) NOT NULL,
    local_start TIME NOT NULL,
    local_end TIME NOT NULL,
    CONSTRAINT fk_periods_policy FOREIGN KEY (policy_id) REFERENCES clinic_policy(id),
    CONSTRAINT uq_named_period UNIQUE (policy_id, name)
);

CREATE TABLE recurring_shifts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vet_id INTEGER NOT NULL,
    weekday VARCHAR(16) NOT NULL,
    local_start TIME NOT NULL,
    local_end TIME NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_shift_vet FOREIGN KEY (vet_id) REFERENCES vets(id)
);
CREATE INDEX idx_shift_vet_weekday ON recurring_shifts(vet_id, weekday);

CREATE TABLE availability_exception_days (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vet_id INTEGER NOT NULL,
    local_date DATE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_exception_vet FOREIGN KEY (vet_id) REFERENCES vets(id),
    CONSTRAINT uq_vet_exception_date UNIQUE (vet_id, local_date)
);
CREATE INDEX idx_exception_vet_date ON availability_exception_days(vet_id, local_date);

CREATE TABLE availability_exception_intervals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exception_day_id BIGINT NOT NULL,
    local_start TIME NOT NULL,
    local_end TIME NOT NULL,
    CONSTRAINT fk_exception_interval_day FOREIGN KEY (exception_day_id) REFERENCES availability_exception_days(id) ON DELETE CASCADE
);

CREATE TABLE veterinarian_leave (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vet_id INTEGER NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    reason_category VARCHAR(64) NOT NULL,
    protected_note_payload_id BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_leave_vet FOREIGN KEY (vet_id) REFERENCES vets(id),
    CONSTRAINT fk_leave_protected_payload FOREIGN KEY (protected_note_payload_id) REFERENCES protected_payloads(id),
    CONSTRAINT ck_leave_dates CHECK (end_date >= start_date)
);
CREATE INDEX idx_leave_vet_dates ON veterinarian_leave(vet_id, start_date, end_date);

CREATE TABLE clinic_closures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    owner_reason VARCHAR(255) NOT NULL,
    protected_note_payload_id BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_closure_protected_payload FOREIGN KEY (protected_note_payload_id) REFERENCES protected_payloads(id),
    CONSTRAINT ck_closure_dates CHECK (end_date >= start_date)
);
CREATE INDEX idx_closure_dates ON clinic_closures(start_date, end_date);

CREATE TABLE appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id INTEGER NOT NULL,
    pet_id INTEGER NOT NULL,
    vet_id INTEGER NOT NULL,
    start_at TIMESTAMP WITH TIME ZONE NOT NULL,
    end_at TIMESTAMP WITH TIME ZONE NOT NULL,
    zone_id VARCHAR(64) NOT NULL,
    booking_state VARCHAR(32) NOT NULL,
    outcome_state VARCHAR(32) NOT NULL,
    originating_request_id BIGINT,
    originating_offer_id BIGINT,
    legacy_visit_id INTEGER,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_appointment_owner FOREIGN KEY (owner_id) REFERENCES owners(id),
    CONSTRAINT fk_appointment_pet FOREIGN KEY (pet_id) REFERENCES pets(id),
    CONSTRAINT fk_appointment_vet FOREIGN KEY (vet_id) REFERENCES vets(id),
    CONSTRAINT ck_appointment_interval CHECK (end_at > start_at),
    CONSTRAINT ck_appointment_booking_state CHECK (booking_state IN ('CONFIRMED', 'CANCELLED')),
    CONSTRAINT ck_appointment_outcome_state CHECK (outcome_state IN ('PENDING', 'COMPLETED', 'NO_SHOW'))
);
CREATE INDEX idx_appointment_vet_interval ON appointments(vet_id, start_at, end_at, booking_state);
CREATE INDEX idx_appointment_pet_interval ON appointments(pet_id, start_at, end_at, booking_state);
CREATE INDEX idx_appointment_owner_interval ON appointments(owner_id, start_at, end_at, booking_state);

CREATE TABLE appointment_change_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id BIGINT NOT NULL,
    actor_account_id BIGINT,
    actor_role VARCHAR(32) NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    owner_agreement_recorded BOOLEAN NOT NULL DEFAULT FALSE,
    agreement_medium VARCHAR(32),
    protected_reason_payload_id BIGINT,
    protected_snapshot_payload_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_change_event_appointment FOREIGN KEY (appointment_id) REFERENCES appointments(id),
    CONSTRAINT fk_change_event_actor FOREIGN KEY (actor_account_id) REFERENCES accounts(id),
    CONSTRAINT fk_change_event_reason FOREIGN KEY (protected_reason_payload_id) REFERENCES protected_payloads(id),
    CONSTRAINT fk_change_event_snapshot FOREIGN KEY (protected_snapshot_payload_id) REFERENCES protected_payloads(id)
);
CREATE INDEX idx_change_event_appointment ON appointment_change_events(appointment_id, occurred_at);

-- Initial Clinic Policy Seed Data
INSERT INTO clinic_policy (
    id, zone_id, booking_horizon_days, hold_duration_minutes, owner_notice_minutes,
    start_grid_minutes, clinic_phone, contact_hours, urgent_care_guidance, version, created_at, updated_at
) VALUES (
    1, 'Europe/Amsterdam', 90, 10, 120,
    15, '555-0100', 'Mon-Fri 08:30-17:30',
    'If your pet has severe bleeding, difficulty breathing, or suspected poisoning, please call the clinic directly or visit the nearest emergency animal hospital immediately.',
    0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);

INSERT INTO clinic_operating_intervals (policy_id, weekday, local_start, local_end) VALUES
(1, 'MONDAY', '09:00:00', '17:00:00'),
(1, 'TUESDAY', '09:00:00', '17:00:00'),
(1, 'WEDNESDAY', '09:00:00', '17:00:00'),
(1, 'THURSDAY', '09:00:00', '17:00:00'),
(1, 'FRIDAY', '09:00:00', '17:00:00');

INSERT INTO clinic_allowed_durations (policy_id, duration_minutes) VALUES
(1, 15),
(1, 30),
(1, 45),
(1, 60);

INSERT INTO clinic_named_periods (policy_id, name, local_start, local_end) VALUES
(1, 'MORNING', '09:00:00', '12:00:00'),
(1, 'AFTERNOON', '12:00:00', '17:00:00');

-- Default recurring shifts for standard vets (Mon-Fri 09:00-17:00)
INSERT INTO recurring_shifts (vet_id, weekday, local_start, local_end, version, created_at, updated_at)
SELECT v.id, d.weekday, '09:00:00', '17:00:00', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM vets v
CROSS JOIN (
    VALUES ('MONDAY'), ('TUESDAY'), ('WEDNESDAY'), ('THURSDAY'), ('FRIDAY')
) AS d(weekday);
