CREATE TABLE users (
  id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(100) NOT NULL,
  role     VARCHAR(20) NOT NULL CHECK (role IN ('owner', 'staff')),
  owner_id INTEGER
);
ALTER TABLE users ADD CONSTRAINT fk_users_owners FOREIGN KEY (owner_id) REFERENCES owners (id);

CREATE TABLE scheduling_request (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pet_id            INTEGER NOT NULL,
  owner_id          INTEGER NOT NULL,
  state             VARCHAR(50) NOT NULL,
  reason_text       CLOB NOT NULL,
  availability_text CLOB NOT NULL,
  active_pet_id     INTEGER,
  failed_attempts   INTEGER NOT NULL DEFAULT 0,
  held_vet_id       INTEGER,
  held_start        TIMESTAMP WITH TIME ZONE,
  held_duration     INTEGER,
  created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at        TIMESTAMP WITH TIME ZONE NOT NULL
);
ALTER TABLE scheduling_request ADD CONSTRAINT fk_scheduling_request_pets FOREIGN KEY (pet_id) REFERENCES pets (id);
ALTER TABLE scheduling_request ADD CONSTRAINT fk_scheduling_request_owners FOREIGN KEY (owner_id) REFERENCES owners (id);
ALTER TABLE scheduling_request ADD CONSTRAINT fk_scheduling_request_vets FOREIGN KEY (held_vet_id) REFERENCES vets (id);
ALTER TABLE scheduling_request ADD CONSTRAINT uq_scheduling_request_active_pet UNIQUE (active_pet_id);

CREATE TABLE scheduling_request_event (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id INTEGER NOT NULL,
  from_state VARCHAR(50),
  to_state   VARCHAR(50) NOT NULL,
  actor      VARCHAR(100) NOT NULL,
  action     VARCHAR(100) NOT NULL,
  reason     VARCHAR(255),
  payload    CLOB,
  timestamp  TIMESTAMP WITH TIME ZONE NOT NULL
);
ALTER TABLE scheduling_request_event ADD CONSTRAINT fk_scheduling_request_events_request FOREIGN KEY (request_id) REFERENCES scheduling_request (id);

CREATE TABLE interpretation (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id       INTEGER NOT NULL,
  version          INTEGER NOT NULL,
  provenance       VARCHAR(20) NOT NULL,
  reason_summary   VARCHAR(500),
  estimated_minutes INTEGER,
  care_type        VARCHAR(50),
  specialty        VARCHAR(50),
  preferred_vet_id INTEGER,
  cannot_interpret BOOLEAN NOT NULL DEFAULT FALSE,
  raw_response     CLOB,
  model_tag        VARCHAR(100),
  prompt_version   VARCHAR(50),
  created_at       TIMESTAMP WITH TIME ZONE NOT NULL
);
ALTER TABLE interpretation ADD CONSTRAINT fk_interpretation_request FOREIGN KEY (request_id) REFERENCES scheduling_request (id);
ALTER TABLE interpretation ADD CONSTRAINT fk_interpretation_vets FOREIGN KEY (preferred_vet_id) REFERENCES vets (id);

CREATE TABLE interpretation_window (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  interpretation_id INTEGER NOT NULL,
  kind              VARCHAR(20) NOT NULL,
  date_val          DATE,
  start_date        DATE,
  end_date          DATE,
  day_of_week       VARCHAR(20),
  start_time        TIME,
  end_time          TIME,
  tokens            VARCHAR(255)
);
ALTER TABLE interpretation_window ADD CONSTRAINT fk_interpretation_window_interpretation FOREIGN KEY (interpretation_id) REFERENCES interpretation (id);

CREATE TABLE appointment (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pet_id     INTEGER NOT NULL,
  vet_id     INTEGER NOT NULL,
  start_time TIMESTAMP WITH TIME ZONE NOT NULL,
  duration   INTEGER NOT NULL,
  status     VARCHAR(50) NOT NULL,
  reason     VARCHAR(500),
  request_id INTEGER
);
ALTER TABLE appointment ADD CONSTRAINT fk_appointment_pets FOREIGN KEY (pet_id) REFERENCES pets (id);
ALTER TABLE appointment ADD CONSTRAINT fk_appointment_vets FOREIGN KEY (vet_id) REFERENCES vets (id);
ALTER TABLE appointment ADD CONSTRAINT fk_appointment_request FOREIGN KEY (request_id) REFERENCES scheduling_request (id);

CREATE TABLE appointment_change (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  appointment_id INTEGER NOT NULL,
  actor          VARCHAR(100) NOT NULL,
  action         VARCHAR(100) NOT NULL,
  reason         VARCHAR(255),
  timestamp      TIMESTAMP WITH TIME ZONE NOT NULL
);
ALTER TABLE appointment_change ADD CONSTRAINT fk_appointment_change_appointment FOREIGN KEY (appointment_id) REFERENCES appointment (id);

CREATE TABLE clinic_opening_hour (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clinic_name VARCHAR(100) NOT NULL,
  day_of_week VARCHAR(20) NOT NULL,
  open_time   TIME,
  close_time  TIME,
  closed      BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE clinic_part_of_day (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR(50) NOT NULL,
  start_time TIME NOT NULL,
  end_time   TIME NOT NULL
);

CREATE TABLE clinic_config (
  id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_horizon_days    INTEGER NOT NULL,
  min_duration_minutes    INTEGER NOT NULL,
  max_duration_minutes    INTEGER NOT NULL,
  default_duration_minutes INTEGER NOT NULL,
  grid_interval_minutes   INTEGER NOT NULL,
  time_zone               VARCHAR(50) NOT NULL,
  emergency_phone         VARCHAR(50) NOT NULL
);

CREATE TABLE vet_weekly_block (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vet_id      INTEGER NOT NULL,
  day_of_week VARCHAR(20) NOT NULL,
  start_time  TIME NOT NULL,
  end_time    TIME NOT NULL
);
ALTER TABLE vet_weekly_block ADD CONSTRAINT fk_vet_weekly_block_vets FOREIGN KEY (vet_id) REFERENCES vets (id);

CREATE TABLE vet_exception (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vet_id         INTEGER NOT NULL,
  exception_date DATE NOT NULL,
  unavailable    BOOLEAN NOT NULL DEFAULT TRUE
);
ALTER TABLE vet_exception ADD CONSTRAINT fk_vet_exception_vets FOREIGN KEY (vet_id) REFERENCES vets (id);

CREATE TABLE vet_leave (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vet_id     INTEGER NOT NULL,
  start_date DATE NOT NULL,
  end_date   DATE NOT NULL,
  reason     VARCHAR(255)
);
ALTER TABLE vet_leave ADD CONSTRAINT fk_vet_leave_vets FOREIGN KEY (vet_id) REFERENCES vets (id);

CREATE TABLE clinic_closure (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  closure_date DATE NOT NULL,
  reason       VARCHAR(255)
);

ALTER TABLE visits ADD COLUMN appointment_id INTEGER;
ALTER TABLE visits ADD CONSTRAINT fk_visits_appointments FOREIGN KEY (appointment_id) REFERENCES appointment (id);
