-- V4: Smart Request and Offer Workflow

CREATE TABLE scheduling_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id INTEGER NOT NULL,
    pet_id INTEGER NOT NULL,
    state VARCHAR(64) NOT NULL,
    current_text_revision_id BIGINT,
    current_workflow_revision_id BIGINT,
    appointment_id BIGINT UNIQUE,
    version BIGINT NOT NULL DEFAULT 0,
    submitted_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    closed_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_request_owner FOREIGN KEY (owner_id) REFERENCES owners(id),
    CONSTRAINT fk_request_pet FOREIGN KEY (pet_id) REFERENCES pets(id),
    CONSTRAINT fk_request_appointment FOREIGN KEY (appointment_id) REFERENCES appointments(id)
);
CREATE INDEX idx_request_owner_pet ON scheduling_requests(owner_id, pet_id);
CREATE INDEX idx_request_state ON scheduling_requests(state);

CREATE TABLE active_scheduling_requests (
    pet_id INTEGER PRIMARY KEY,
    request_id BIGINT NOT NULL UNIQUE,
    CONSTRAINT fk_active_pet FOREIGN KEY (pet_id) REFERENCES pets(id),
    CONSTRAINT fk_active_request FOREIGN KEY (request_id) REFERENCES scheduling_requests(id) ON DELETE CASCADE
);

CREATE TABLE text_revisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT NOT NULL,
    revision_number INTEGER NOT NULL,
    submitted_at TIMESTAMP WITH TIME ZONE NOT NULL,
    prose_payload_id BIGINT NOT NULL UNIQUE,
    consent_payload_id BIGINT NOT NULL UNIQUE,
    CONSTRAINT fk_text_rev_request FOREIGN KEY (request_id) REFERENCES scheduling_requests(id) ON DELETE CASCADE,
    CONSTRAINT fk_text_rev_prose FOREIGN KEY (prose_payload_id) REFERENCES protected_payloads(id),
    CONSTRAINT fk_text_rev_consent FOREIGN KEY (consent_payload_id) REFERENCES protected_payloads(id),
    CONSTRAINT uq_request_text_rev UNIQUE (request_id, revision_number)
);
CREATE INDEX idx_text_rev_request ON text_revisions(request_id);

CREATE TABLE interpretations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text_revision_id BIGINT NOT NULL UNIQUE,
    source VARCHAR(32) NOT NULL,
    model_identifier VARCHAR(128),
    raw_payload_id BIGINT UNIQUE,
    validated_payload_id BIGINT UNIQUE,
    validation_state VARCHAR(32) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_interpretation_text_rev FOREIGN KEY (text_revision_id) REFERENCES text_revisions(id) ON DELETE CASCADE,
    CONSTRAINT fk_interpretation_raw FOREIGN KEY (raw_payload_id) REFERENCES protected_payloads(id),
    CONSTRAINT fk_interpretation_validated FOREIGN KEY (validated_payload_id) REFERENCES protected_payloads(id)
);

CREATE TABLE workflow_revisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT NOT NULL,
    revision_number INTEGER NOT NULL,
    text_revision_id BIGINT,
    interpretation_id BIGINT,
    state VARCHAR(64) NOT NULL,
    reason_payload_id BIGINT NOT NULL UNIQUE,
    duration_minutes INTEGER NOT NULL,
    preferred_vet_id INTEGER,
    required_specialty_id INTEGER,
    urgency VARCHAR(32) NOT NULL,
    automatic_offer_count INTEGER NOT NULL DEFAULT 0,
    confirmed_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_workflow_rev_request FOREIGN KEY (request_id) REFERENCES scheduling_requests(id) ON DELETE CASCADE,
    CONSTRAINT fk_workflow_rev_text FOREIGN KEY (text_revision_id) REFERENCES text_revisions(id),
    CONSTRAINT fk_workflow_rev_interpretation FOREIGN KEY (interpretation_id) REFERENCES interpretations(id),
    CONSTRAINT fk_workflow_rev_reason FOREIGN KEY (reason_payload_id) REFERENCES protected_payloads(id),
    CONSTRAINT fk_workflow_rev_vet FOREIGN KEY (preferred_vet_id) REFERENCES vets(id),
    CONSTRAINT fk_workflow_rev_specialty FOREIGN KEY (required_specialty_id) REFERENCES specialties(id),
    CONSTRAINT uq_request_workflow_rev UNIQUE (request_id, revision_number)
);
CREATE INDEX idx_workflow_rev_request ON workflow_revisions(request_id);

CREATE TABLE availability_windows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_revision_id BIGINT NOT NULL,
    classification VARCHAR(32) NOT NULL,
    shape VARCHAR(32) NOT NULL,
    local_date DATE,
    range_start DATE,
    range_end DATE,
    weekdays VARCHAR(128),
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    source_text TEXT NOT NULL,
    resolution_note TEXT,
    CONSTRAINT fk_window_workflow_rev FOREIGN KEY (workflow_revision_id) REFERENCES workflow_revisions(id) ON DELETE CASCADE
);
CREATE INDEX idx_window_workflow_rev ON availability_windows(workflow_revision_id);

CREATE TABLE offer_exclusions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_revision_id BIGINT NOT NULL,
    vet_id INTEGER NOT NULL,
    start_at TIMESTAMP WITH TIME ZONE NOT NULL,
    end_at TIMESTAMP WITH TIME ZONE NOT NULL,
    offer_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_exclusion_workflow_rev FOREIGN KEY (workflow_revision_id) REFERENCES workflow_revisions(id) ON DELETE CASCADE,
    CONSTRAINT fk_exclusion_vet FOREIGN KEY (vet_id) REFERENCES vets(id),
    CONSTRAINT uq_exclusion_slot UNIQUE (workflow_revision_id, vet_id, start_at, end_at)
);
CREATE INDEX idx_exclusion_workflow_rev ON offer_exclusions(workflow_revision_id);

CREATE TABLE background_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_type VARCHAR(32) NOT NULL,
    text_revision_id BIGINT UNIQUE,
    workflow_revision_id BIGINT UNIQUE,
    state VARCHAR(32) NOT NULL,
    run_sequence INTEGER NOT NULL DEFAULT 1,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    calendar_retry_count INTEGER NOT NULL DEFAULT 0,
    lease_token VARCHAR(64),
    lease_until TIMESTAMP WITH TIME ZONE,
    available_at TIMESTAMP WITH TIME ZONE,
    started_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    calendar_revision BIGINT,
    outcome_category VARCHAR(64),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_job_text_rev FOREIGN KEY (text_revision_id) REFERENCES text_revisions(id) ON DELETE CASCADE,
    CONSTRAINT fk_job_workflow_rev FOREIGN KEY (workflow_revision_id) REFERENCES workflow_revisions(id) ON DELETE CASCADE
);
CREATE INDEX idx_job_state_available ON background_jobs(state, available_at);
CREATE INDEX idx_job_lease ON background_jobs(lease_until);

CREATE TABLE offers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT NOT NULL,
    workflow_revision_id BIGINT NOT NULL,
    owner_id INTEGER NOT NULL,
    pet_id INTEGER NOT NULL,
    vet_id INTEGER NOT NULL,
    origin VARCHAR(32) NOT NULL,
    start_at TIMESTAMP WITH TIME ZONE NOT NULL,
    end_at TIMESTAMP WITH TIME ZONE NOT NULL,
    zone_id VARCHAR(64) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    state VARCHAR(32) NOT NULL,
    automatic_attempt_number INTEGER,
    calendar_revision BIGINT NOT NULL,
    match_explanation TEXT NOT NULL,
    appointment_id BIGINT UNIQUE,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_offer_request FOREIGN KEY (request_id) REFERENCES scheduling_requests(id) ON DELETE CASCADE,
    CONSTRAINT fk_offer_workflow_rev FOREIGN KEY (workflow_revision_id) REFERENCES workflow_revisions(id),
    CONSTRAINT fk_offer_owner FOREIGN KEY (owner_id) REFERENCES owners(id),
    CONSTRAINT fk_offer_pet FOREIGN KEY (pet_id) REFERENCES pets(id),
    CONSTRAINT fk_offer_vet FOREIGN KEY (vet_id) REFERENCES vets(id),
    CONSTRAINT fk_offer_appointment FOREIGN KEY (appointment_id) REFERENCES appointments(id),
    CONSTRAINT ck_offer_interval CHECK (end_at > start_at),
    CONSTRAINT ck_offer_origin CHECK (origin IN ('AUTOMATIC', 'STAFF_ASSISTED')),
    CONSTRAINT ck_offer_state CHECK (state IN ('HELD', 'ACCEPTED', 'REJECTED', 'EXPIRED', 'RELEASED'))
);
CREATE INDEX idx_offer_request ON offers(request_id);
CREATE INDEX idx_offer_vet_interval ON offers(vet_id, start_at, end_at, state);
CREATE INDEX idx_offer_pet_interval ON offers(pet_id, start_at, end_at, state);
CREATE INDEX idx_offer_owner_interval ON offers(owner_id, start_at, end_at, state);
CREATE INDEX idx_offer_expires ON offers(expires_at, state);

ALTER TABLE scheduling_requests ADD CONSTRAINT fk_request_text_rev FOREIGN KEY (current_text_revision_id) REFERENCES text_revisions(id);
ALTER TABLE scheduling_requests ADD CONSTRAINT fk_request_workflow_rev FOREIGN KEY (current_workflow_revision_id) REFERENCES workflow_revisions(id);
