-- V5: Staff Fallback Queue

CREATE TABLE queue_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT NOT NULL UNIQUE,
    workflow_revision_id BIGINT,
    state VARCHAR(32) NOT NULL,
    awaiting_reason VARCHAR(64),
    fallback_reason VARCHAR(64) NOT NULL,
    urgency VARCHAR(32) NOT NULL,
    assignee_account_id BIGINT,
    last_contact_at TIMESTAMP WITH TIME ZONE,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    resolved_at TIMESTAMP WITH TIME ZONE,
    closed_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_queue_request FOREIGN KEY (request_id) REFERENCES scheduling_requests(id) ON DELETE CASCADE,
    CONSTRAINT fk_queue_workflow_rev FOREIGN KEY (workflow_revision_id) REFERENCES workflow_revisions(id),
    CONSTRAINT fk_queue_assignee FOREIGN KEY (assignee_account_id) REFERENCES accounts(id),
    CONSTRAINT ck_queue_state CHECK (state IN ('NEW', 'IN_REVIEW', 'AWAITING_OWNER', 'RESOLVED', 'CLOSED')),
    CONSTRAINT ck_queue_awaiting_reason CHECK (awaiting_reason IS NULL OR awaiting_reason IN ('CONTACT_REQUIRED', 'INTERPRETATION_CONFIRMATION', 'PORTAL_OFFER')),
    CONSTRAINT ck_queue_urgency CHECK (urgency IN ('ROUTINE', 'PRIORITY', 'EMERGENCY_SUSPECTED'))
);

CREATE INDEX idx_queue_state ON queue_items(state);
CREATE INDEX idx_queue_urgency ON queue_items(urgency);
CREATE INDEX idx_queue_assignee ON queue_items(assignee_account_id);
CREATE INDEX idx_queue_fallback_reason ON queue_items(fallback_reason);
CREATE INDEX idx_queue_created ON queue_items(created_at);
CREATE INDEX idx_queue_updated ON queue_items(updated_at);

CREATE TABLE contact_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    queue_item_id BIGINT NOT NULL,
    actor_account_id BIGINT NOT NULL,
    attempted_at TIMESTAMP WITH TIME ZONE NOT NULL,
    outcome VARCHAR(64) NOT NULL,
    note_payload_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_contact_queue_item FOREIGN KEY (queue_item_id) REFERENCES queue_items(id) ON DELETE CASCADE,
    CONSTRAINT fk_contact_actor FOREIGN KEY (actor_account_id) REFERENCES accounts(id),
    CONSTRAINT fk_contact_note FOREIGN KEY (note_payload_id) REFERENCES protected_payloads(id)
);

CREATE INDEX idx_contact_queue_item ON contact_attempts(queue_item_id);
CREATE INDEX idx_contact_attempted_at ON contact_attempts(attempted_at);
