-- V7: Appointment Outcomes and Legacy Reconciliation

ALTER TABLE visits ADD COLUMN provenance VARCHAR(32) DEFAULT 'LEGACY' NOT NULL;
ALTER TABLE visits ADD COLUMN appointment_id BIGINT;
ALTER TABLE visits ADD COLUMN vet_id INTEGER;
ALTER TABLE visits ADD COLUMN protected_clinical_payload_id BIGINT;
ALTER TABLE visits ADD COLUMN outcome_event_id BIGINT;

ALTER TABLE visits ADD CONSTRAINT fk_visit_appointment FOREIGN KEY (appointment_id) REFERENCES appointments(id);
ALTER TABLE visits ADD CONSTRAINT fk_visit_vet FOREIGN KEY (vet_id) REFERENCES vets(id);
ALTER TABLE visits ADD CONSTRAINT fk_visit_clinical_payload FOREIGN KEY (protected_clinical_payload_id) REFERENCES protected_payloads(id);

CREATE TABLE appointment_outcome_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id BIGINT NOT NULL,
    event_type VARCHAR(32) NOT NULL,
    actor_account_id BIGINT,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    previous_outcome VARCHAR(32),
    new_outcome VARCHAR(32) NOT NULL,
    resulting_visit_id INTEGER,
    reason_payload_id BIGINT,
    clinical_payload_id BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_outcome_event_appointment FOREIGN KEY (appointment_id) REFERENCES appointments(id),
    CONSTRAINT fk_outcome_event_actor FOREIGN KEY (actor_account_id) REFERENCES accounts(id),
    CONSTRAINT fk_outcome_event_visit FOREIGN KEY (resulting_visit_id) REFERENCES visits(id),
    CONSTRAINT fk_outcome_event_reason FOREIGN KEY (reason_payload_id) REFERENCES protected_payloads(id),
    CONSTRAINT fk_outcome_event_clinical FOREIGN KEY (clinical_payload_id) REFERENCES protected_payloads(id),
    CONSTRAINT ck_outcome_event_type CHECK (event_type IN ('COMPLETED', 'NO_SHOW', 'CORRECTION'))
);

ALTER TABLE visits ADD CONSTRAINT fk_visit_outcome_event FOREIGN KEY (outcome_event_id) REFERENCES appointment_outcome_events(id);

CREATE INDEX idx_outcome_event_appointment ON appointment_outcome_events(appointment_id, occurred_at);
CREATE INDEX idx_visits_appointment ON visits(appointment_id);
CREATE INDEX idx_visits_date_provenance ON visits(visit_date, provenance);
